openzfsonwindows/openzfs

lib/libspl/os/windows/posix.c

Share flag (dwShareMode) changed for CreateFile.
I took references from ZFSin.

share flag fixed for CreateFile

---

include/os/windows/spl/sys/condvar.h

In file include/os/windows/spl/sys/condvar.h, there is macro definition for 'cv_timedwait_idle_hires_'. Compared to ZFSin, the flag parameter is changed to include PCATCH (same value as CALLOUT_FLAG_ABSOLUTE).
#define cv_timedwait_idle_hires(cvp, mp, tim, res, flag)
cv_timedwait_hires(cvp, mp, tim, res, (flag)|PCATCH)
The threads zthr_procedure(),dbuf_evict_thread call into this macro/function. In cv_timedwait_hires() (in file spl-condvar.c), the
condition check for flag CALLOUT_FLAG_ABSOLUTE is becoming true. so the 'timeout' value is getting changed to incorrect value and the thread does not wait enough (callers pass 1 sec and not absolute value) on the lock event.

CPU Hog Fix

---

module/os/windows/zfs/vdev_disk.c

Zpool Import functionality is broken as reported in issue#14. It fails to read vdev label on Windows 2019 but succeeds in windows 10.
Currently, the read IRP's are sent to FileObject->DeviceObject. On windows 2019, The FileObject->DeviceObject->DriverObject->DriverName is different based on the disk device name. For device names like \??\PHYSICALDRIVE1, it is \Driver\disk. For scsi device names (eg \??\scsi#disk&ven_vbox&prod_harddisk#4&2617aeae&0&020000#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}, it is \Driver\storahci.
So assigning the dvd->vd_DeviceObject to the driver below \Driver\partmgr in the device stack as in ZFSin which would be \Driver\disk.

zpool import not working

---

module/os/windows/zfs/zfs_vnops_windows_mount.c

Zpool destroy is crashing due to reference count issue.

Zpool destroy is crashing

---

module/os/windows/zfs/zfs_windows_zvol_scsi.c

Fix for Data Miscompare/validation Error as reported in issue https://github.com/openzfsonwindows/openzfs/issues/27.
Fix:-
The uio sector offset was not set during read/write.

Fix for Data Miscompare/validation Error.

---

module/os/windows/zfs/zfs_windows_zvol_wmi.c

Issue:- The GetDiscoveredPortAttributes() WMI method was not implemented for the WMI class MSFC_HBAAdapterMethods. This was causing problem with SCVMM setup.
Fix:- Implemented the GetDiscoveredPortAttributes method for the WMI class. 
To Test:- Execute the below WMI query from Powershell and it should not return any error.
Get-WMIObject -Class MSFC_HBAAdapterMethods -Namespace root\wmi | ForEach-Object {$_.GetDiscoveredPortAttributes(0,0)}

ssv-20352 Handled WMI method GetDiscoveredPortAttributes()

---

module/os/windows/zfs/zvol_os.c

This was earlier committed into zfsin:- https://github.com/openzfsonwindows/ZFSin/issues/341
Now pushing into OpenZfs as well..

assign targetId and lun after zvol is open

---

lib/libzutil/zutil_device_path.c

Not able to remove devices from zpool.
----------------------------------------------------------------------------------------
Z:\x64-Debug\bin>zpool create pool1 PHYSICALDRIVE1 PHYSICALDRIVE2
Expanded path to '\\?\PHYSICALDRIVE1'
Expanded path to '\\?\PHYSICALDRIVE2'
working on dev '#1048576#4284481536#\\?\PHYSICALDRIVE1'
setting path here '/dev/physicaldrive1'
setting physpath here '#1048576#4284481536#\\?\PHYSICALDRIVE1'
working on dev '#1048576#32201768960#\\?\PHYSICALDRIVE2'
setting path here '/dev/physicaldrive2'
setting physpath here '#1048576#32201768960#\\?\PHYSICALDRIVE2'
Z:\x64-Debug\bin>zpool add pool1 PHYSICALDRIVE3
Expanded path to '\\?\PHYSICALDRIVE3'
working on dev '#1048576#1667235840#\\?\PHYSICALDRIVE3'
setting path here '/dev/physicaldrive3'
setting physpath here …

case insensitive path compare for windows zpool devices

---

module/zfs/zfs_ioctl.c

As mentioned in https://github.com/openzfsonwindows/openzfs/issues/64 , the File_Object minor value is not correctly set in the zfs device object state. So the minor value is not found in the ZFS device object state list during close handle and hence does not get released.

Setting the FILE_OBJECT minor value in the zfs device object state

---

module/os/windows/zfs/zfs_ioctl_os.c

As described in https://github.com/openzfsonwindows/openzfs/issues/64, the function zfsdev_private_set_state()  corrupts the FILE_OBJECT passed in the 'priv' parameter. As commented in the function, this function is not supposed to do anything. So defined it as empty.

fixed FILE_OBJECT corruption issue for the ZFS device object

---

cmd/zdb/zdb.c
include/os/windows/zfs/sys/kstat_windows.h
include/sys/arc_impl.h
module/os/windows/zfs/arc_os.c
module/zfs/arc.c

As described in https://github.com/openzfsonwindows/openzfs/issues/63, the arc limit values gets truncate for larger numbers. As windows is LLP64, using uint64_t for the arc limit values.

changing the datatype of arc limit values to uint64_t

---

include/sys/dsl_pool.h
module/zfs/dsl_pool.c

changed zfs_wrlog_data_max parameter to uint64_t to avoid overflow.
The default value of zfs_wrlog_data_max = zfs_dirty_data_max * 2;
=4GB * 2 which overflows long and this impacts I/O performance.

changed zfs_wrlog_data_max parameter to uint64_t

---

include/os/windows/spl/sys/lookasidelist.h
module/os/windows/spl/CMakeLists.txt
module/os/windows/spl/spl-lookasidelist.c
module/os/windows/zfs/abd_os.c
module/os/windows/zfs/arc_os.c

As described in issue https://github.com/openzfsonwindows/openzfs/issues/79 , Windows ZFS performance of  128k sequential write on zvol of volblocksize=128k was much less compared to Linux. Xperf trace showed much contention in abd_alloc_chunks(). So we tested by replacing kmem_cache with lookasidelist for abd chunk cache
and performance gain was over 40%. Lookasidelist is the windows implementation of object cache similar to kmem_cache on Linux.
This is the minimal implementation and further code review/changes would be required before integrating into the code base.
Reference:
https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/using-lookaside-lists

using lookasidelist for abd_chunk_cache

---

module/os/windows/zfs/vdev_disk.c

As seen in issue https://github.com/openzfsonwindows/openzfs/issues/86, the IO buffer seemed to be locked by the MDL in the completion routine handler. Moving the MDL unlock call up before freeing the buffer.

unlock the IO buffer in the MDL before freeing it

---

module/os/windows/zfs/vdev_disk.c

It fixes https://github.com/openzfsonwindows/openzfs/issues/85

IoStatus from IRP to be used to set zio->io_error

---

include/os/windows/spl/sys/kmem.h
include/os/windows/spl/sys/systm.h
include/os/windows/spl/sys/vmem.h
module/os/windows/spl/spl-kmem.c
module/os/windows/spl/spl-vmem.c
module/os/windows/spl/spl-windows.c

As seen in issue https://github.com/openzfsonwindows/openzfs/issues/92, the bsd timer fires after driver unload and bugcheck. So explicitly cancel the timers at unload.

Cancel the bsd-timers before driver unload

---

module/os/windows/zfs/zvol_os.c

Fixed it by calling the StorPortNotification for Buschange

 After zpool export , zvols still appear in the disk management

---

module/os/windows/zfs/zfs_debug.c

Add a check to dprintf that will avoid trying to write to the debug log if we are in a IRQL of DISPATCH_LEVEL or higher.
Otherwise we will get a BSOD when __zfs_dbgmsg tries to grab a mutex.
https://github.com/openzfsonwindows/openzfs/issues/103

Skip __zfs_dbgmsg in a DPC

---

module/os/windows/zfs/zfs_ioctl_os.c
module/os/windows/zfs/zfs_vnops_windows.c

https://github.com/openzfsonwindows/openzfs/issues/102

ioctldeviceobject cleanup moved to IRP_MJ_CLOSE, TO avoid DV violation

---

module/os/windows/zfs/sysctl_os.c

As described in https://github.com/openzfsonwindows/openzfs/issues/124, DV reports mem leak during uninstall. The string 'sysctl_os_RegistryPath' is allocated again and not freed.

fix mem leak in registry notify change handler

---

include/os/freebsd/linux/compiler.h
include/os/freebsd/spl/sys/atomic.h
include/os/linux/spl/sys/vmsystm.h
include/os/windows/spl/sys/atomic.h
module/zfs/zfs_ioctl.c

Upstream started using a set of common memory barriers that we don't have.
So here's an implementation for comment.

Windows: Cleanup: Make memory barrier definitions consistent across kernels

---

include/os/freebsd/zfs/sys/zfs_znode_impl.h
include/os/linux/zfs/sys/zfs_znode_impl.h
include/os/windows/zfs/sys/zfs_znode_impl.h
include/sys/zfs_znode.h
module/os/freebsd/zfs/zfs_ctldir.c
module/os/freebsd/zfs/zfs_vfsops.c
module/os/freebsd/zfs/zfs_vnops_os.c
module/os/linux/zfs/zfs_acl.c
module/os/linux/zfs/zfs_ctldir.c
module/os/linux/zfs/zfs_vfsops.c
module/os/linux/zfs/zfs_vnops_os.c
module/os/linux/zfs/zpl_ctldir.c
module/os/linux/zfs/zpl_file.c
module/os/linux/zfs/zpl_super.c
module/os/linux/zfs/zpl_xattr.c
module/os/windows/zfs/zfs_acl.c
module/os/windows/zfs/zfs_ctldir.c
module/os/windows/zfs/zfs_vfsops.c
module/os/windows/zfs/zfs_vnops_os.c
module/os/windows/zfs/zfs_vnops_windows.c
module/os/windows/zfs/zfs_vnops_windows_lib.c
module/zfs/zfs_vnops.c

This needs going over.
I don't know if I've replaced the right variables from ZFS_VERIFY_ZP_ERROR, and there may be an unnecessary error added.
Also do we need to convert errors to some windows specific format?

Windows: zfs_enter rework

---

.github/workflows/windows-build-test.yml

This fixes up the windows test runner a bit to reduce the deprecation warnings we were getting.
It also changes the tests so that only the tests that currently pass are run, so this checks for regressions mostly.
You an still run all of the tests manually if you need to.
Finally it also runs a test to recreate the ads issue I have been having.
(This may need to be vised to something smaller that triggers the same issue)

Windows test runner fixes

---

include/sys/zil.h
module/os/freebsd/zfs/zvol_os.c
module/os/linux/zfs/zvol_os.c
module/os/windows/zfs/zvol_os.c
module/zfs/zil.c

I need to squash my commits but how is this?

Windows: Optionally skip zil_close during zvol_create_minor_impl

---

CMakeLists.txt

I fixed some of the issues, but we were ignoring them before so we could just ignore them again.
Unless someone wants to go through and fix them.

Ignore Wint-conversion errors

---

include/os/freebsd/spl/sys/simd_aarch64.h
include/os/freebsd/spl/sys/simd_arm.h
include/os/freebsd/spl/sys/simd_x86.h
include/os/freebsd/spl/sys/vnode.h
module/icp/algs/blake3/blake3.c
module/icp/algs/blake3/blake3_generic.c
module/icp/algs/blake3/blake3_impl.c
module/icp/algs/sha2/sha256_impl.c
module/icp/algs/sha2/sha512_impl.c
module/os/freebsd/zfs/zfs_vnops_os.c
module/zcommon/zfs_fletcher.c
module/zcommon/zfs_prop.c
module/zfs/vdev_raidz_math.c

When resolving the conflict I reorganised our includes in module/icp/algs/sha2/sha256_impl.c and module/icp/algs/sha2/sha512_impl.c to match upstream
- Andrew Innes
Add missing machine/md_var.h to spl/sys/simd_aarch64.h and spl/sys/simd_arm.h
In spl/sys/simd_x86.h, PCB_FPUNOSAVE exists only on amd64, use PCB_NPXNOSAVE on i386
In FreeBSD sys/elf_common.h redefines AT_UID and AT_GID on FreeBSD, we need a hack in vnode.h similar to Linux. sys/simd.h needs to be included early.
In zfs_freebsd_copy_file_range() we pass a (size_t *)lenp to zfs_clone_range() that expects a (uint64_t *)
Allow compiling armv6 world by limiting ARM macros in sha256_impl.c and sha512_impl.c to __ARM_ARCH > 6
Reviewed-by: Alexander Motin <mav@FreeBSD.org>
Reviewed-by: Tino Reichardt <milky-zfs@mcmilk.de>
Reviewed-by: …

Miscellaneous FreBSD compilation bugfixes

---

module/os/windows/zfs/zfs_windows_zvol_wmi.c

As reported in https://github.com/openzfsonwindows/openzfs/issues/243, ExecuteWmiMethod() bug checks when WMI method is not implemented.

Do not bug check when any WMI method is not implemented.

---

module/os/windows/debug.c

The `printBuffer` function was not correctly limiting writes to buffer, we passed the full buffer size to `_vsnprintf_s` despite not starting at the first element. This allows for a buffer overflow of 17 bytes after the buffer.
The code is changed to account for this and to truncate the buffer and mark the end with a "TRUNC\n" if the buffer is not large enough.
With the current buffer size, the largest printable string is 1005 bytes (1024 - 18 byte header - 1 byte zero termination). Anything larger will result in the string being truncated.

printBuffer: Fix stack overflow

---

module/Makefile.in

Link: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=b341b20d648bb7e9a3307c33163e7399f0913e66
Fixes the checkstyle test failure.
cherry-picked from upstream

check-zstd-symbols: also ignore __pfx_ symbols

---

.github/workflows/windows-build-test.yml
contrib/windows/tests/regression.py
contrib/windows/tests/tests.py
contrib/windows/tests/utils.py

I used this test when diagnosing #281 and think it would be a good addition.
This tests file sizes when pre-allocating a file.
Expected values have been confirmed on NTFS, ReFS and FAT32. This test currently does not work on a SMB share with the Samba server [because it reports a fixed cluster size based on a configuration option](https://bugzilla.samba.org/show_bug.cgi?id=7436) instead of getting the correct value from the underlying file system. ksmbd does not have the same issue, it correctly gets the values from the file system. So far this is untested with Windows SMB shares.
This also makes `tests.py` use some helpers from `utils.py`.
Note that currently the test does not pass yet because #281 needs more fixing.

tests: Add a pre-allocation test

---

module/os/windows/zfs/zfs_vfsops.c
module/os/windows/zfs/zfs_vnops_windows.c

During unmount `zfsvfs` is destroyed and the pointer is zeroed in the VCB. There is however still a copy of the pointer in the DCB.
Windows can still call into `zfs_AcquireForLazyWrite`, through `CcMgr` after unmount and this would use the already freed `zfsvfs` pointer.
To fix this we set the pointer to zero in the DCB and add a zero check in `zfs_AcquireForLazyWrite`, `zfs_AcquireForReadAhead` and `fastio_acquire_for_mod_write`.
fixes #282

Fix use-after-free of zfsvfs after unmount

---

.github/workflows/windows-build-test.yml
contrib/windows/tests/tests.py
contrib/windows/tests/utils.py

This cleans up the code of `tests.py` and makes it use the new functions from `utils.py`. This also makes the test sleep much less, ~~which is only still required before destroying the pool due to https://github.com/openzfsonwindows/openzfs/issues/282~~

tests: Clean up the existing tests.py

---

contrib/windows/parsedump/parsedump.py

Instead of using `dt` on `OpenZFS!cbuf` and checking the output we can just use `poi(OpenZFS!cbuf)` in the `.writemem` command.

parsedump: Simplify by using poi instead of regex

---

.github/workflows/windows-build-test.yml
contrib/windows/tests/tests.py

Add more snapshot tests

---

contrib/windows/tests/tests.py

The test currently exports all pools which makes it impossible to run other tests in parallel on a different drive letter. Instead we should only export the pool created by the test.

tests: Export specific pool in the snapshot tests

---

contrib/windows/parsedump/parsedump.py

Add more locations the debugger might be in

Search for debugger

---

contrib/windows/parsedump/parsedump.py

Uses a string join instead to build the command string.

parsedump: Make checkstyle happy by splitting the long Lines

---

contrib/windows/tests/utils.py

The return value was annotated with `pathlib.Path` but `ZpoolInfo` is returned instead.

tests: Fix return type of zpool_create

---

module/os/windows/spl/spl-time.c

`KeQueryTickCount` seems to only have a 15.625ms resolution unless the interrupt timer frequency is increased, which should be avoided due to power usage.
Instead, this switches the `zfs_lbolt`, `gethrtime` and `random_get_bytes` to use `KeQueryPerformanceCounter`.
On my system this gives a 100ns resolution.

spl-time: Use KeQueryPerformanceCounter instead of KeQueryTickCount

---

module/os/windows/spl/spl-time.c
module/os/windows/spl/spl-vnode.c

This removes leaving the `vnode_all_list_lock` in the loop as that is not needed. It also only enters the `v_mutex` of nodes that are not `VNODE_DEAD` yet.
This converts part of the loop to a new function called `flush_file_objects` to make it more readable.
This also removes the restart of the loop, which is safe because `vnode_all_list_lock` is never unlocked.

vflush: Speed up reclaim by doing less in the loop

---

CMakeLists.txt
contrib/windows/cmake/GetGitRevisionDescription.cmake
contrib/windows/cmake/GetGitRevisionDescription.cmake.in

The current build does only update `zfs_gitrev.h` on the first configuration run but then not change it when the commit changes.
To fix this we need to call `get_git_head_revision`.
This also updates `GetGitRevisionDescription` to the latest version from https://github.com/rpavlik/cmake-modules/tree/d66fc5dec3eaea3a4f9778ceeeb65cbec490b5b9

cmake: make GetGitRevisionDescription work

---

module/os/windows/spl/spl-kmem.c
module/os/windows/spl/spl-vmem.c

As discussed in https://github.com/openzfsonwindows/openzfs/issues/336, the memory allocation failed during init. The free thread was not running and its cond var/mutex was not initialized. So checking free thread is running before trying to set the memory pressure.

Check SPL free thread is running before trying to set memory pressure.

---

module/os/windows/zfs/zfs_windows_zvol_scsi.c

Issue: As discussed in https://github.com/openzfsonwindows/openzfs/issues/358, there was a bugcheck when kmem cache re-allocated same memory for IO remove lock.
Cause: zvol_assign_targetid() allocates memory for the IO_REMOVE_LOCK structure from kmem cache. Once it is freed, it can allocate the same cached memory in the next allocation call. This is making the driver verifier to flag that the same IO_REMOVE_LOCK structure is reinitialized second time.
Repro steps:
Create and destroy a zvol multiple times in a loop.
Fix:
Allocated remove lock memory using ExAllocatePoolWithTag(). DV correctly tracks this as a new instance of the remove lock and does not complain.

Allocate memory for Remove lock using ExAllocatePoolWithTag().
