cmd/os/windows/zfsinstaller/zfsinstaller.cpp
include/os/windows/Trace.h
include/os/windows/zfs/sys/zfs_context_os.h
module/os/windows/CMakeLists.txt
module/os/windows/debug.c
module/os/windows/spl/CMakeLists.txt
module/os/windows/spl/spl-kmem.c
module/os/windows/spl/spl-kstat.c
module/os/windows/spl/spl-seg_kmem.c
module/os/windows/spl/spl-vmem.c
module/os/windows/spl/spl-vnode.c
module/os/windows/spl/spl-windows.c
module/os/windows/zfs/CMakeLists.txt
module/os/windows/zfs/zfs_ioctl_os.c
module/os/windows/zfs/zfs_windows_zvol_scsi.c
module/os/windows/zfs/zvol_os.c

-> Steps for Enable WPP tracing
1. Build and install OpenZFS
2. RUN 'zfsinstaller.exe trace' to create autosession
3. Reboot
4. .etl file created in driver folder 
-> Created three functions in CmakeList.txt
1. 'wpp' function recursively call 'tracewpp' function to create .tmh file for give file
2. 'set_file_properties' function set the WPPFILE macro for each file of current folder

Enable WPP tracing for module/os/windows folder

---

CMakeSettings.json
lib/libzpool/CMakeLists.txt

-> Edit lib/libzpool/CmakeList.txt 
add_definitionss for (**-DDEBUG -UNDEBUG -DZFS_DEBUG**)  macros
-> Edit CmakeSettings.json to view Release drop down

Changes for building Release binaries

---

cmd/os/windows/zfsinstaller/zfsinstaller.cpp
include/sys/zfs_ioctl.h
module/os/windows/CMakeLists.txt
module/os/windows/OpenZFS.man
module/os/windows/spl/spl-kstat.c
module/os/windows/zfs/arc_os.c
module/os/windows/zfs/zfs_ioctl_os.c

- Three perfmon counter set added:
1. OpenZFS Zpool
2. OpenZFS Vdev
3. OpenZFS Cache

Perfmon counters added

---

CMakeLists.txt
cmd/os/windows/kstat/CMakeLists.txt
cmd/os/windows/kstat/resource.h
cmd/os/windows/kstat/resource.rc
cmd/os/windows/zfsinstaller/CMakeLists.txt
cmd/os/windows/zfsinstaller/resource.h
cmd/os/windows/zfsinstaller/resource.rc
cmd/zdb/CMakeLists.txt
cmd/zdb/os/windows/resource.h
cmd/zdb/os/windows/resource.rc
cmd/zfs/CMakeLists.txt
cmd/zfs/os/windows/resource.h
cmd/zfs/os/windows/resource.rc
cmd/zpool/CMakeLists.txt
cmd/zpool/os/windows/resource.h
cmd/zpool/os/windows/resource.rc
cmd/zstream/CMakeLists.txt
cmd/zstream/os/windows/resource.h
cmd/zstream/os/windows/resource.rc
module/os/windows/CMakeLists.txt
module/os/windows/README.md
module/os/windows/resource.h
module/os/windows/resource.rc

Added file version, copyright, etc to OpenZFS driver and other executables.

File version added

---

include/os/windows/spl/sys/lookasidelist.h
module/os/windows/spl/spl-lookasidelist.c
module/os/windows/zfs/abd_os.c

Added kstat for lookasidelist.

added kstat for lookasidelist

---

README.md

Add a large header to the main README.md to inform
users that this is not production-ready software and that
they should be aware of the risks of using it with critical data.
The current README.md does not give any indication that OpenZFS for windows is still in a pre-release state.
Potential users should be well informed of any potential data loss that may result from using a system not ready for production.
Adds a large warning header to the start of the README.md (shown to users browsing the project on Github).
N/A

Add large "pre-release software" warning header to README.md

---

.gitignore

Makes it easier to commit changed files after a build

Ignore Visual Studio files

---

.github/workflows/windows-build-test.yml

Automated builds should make it easier for other people to test out development versions of OpenZFS
They should also let us see if pull requests compile before me merge them
Workflow for windows builds on github

Workflow for windows builds w/ output

---

module/os/windows/.gitignore

This prevents autogenerated files from accidentally getting added to a commit.
Adds files that are generated at build time for windows perfcount to .gitignore

Ignore autogenerated files

---

.github/workflows/windows-build-test.yml
contrib/windows/Inno.Setup/ZFSInstall-debug.iss

Automation for building dev builds may help with development
Modifies the windows test build workflow to download Inno Setup and generate an installer.

Make Inno setup installer in workflow

---

cmd/zdb/CMakeLists.txt

This never got PR'd and merged
https://github.com/openzfsonwindows/openzfs/issues/73

ZDB -d option resolved

---

include/os/windows/zfs/sys/zfs_context_os.h
include/sys/spa.h
lib/libzpool/kernel.c
module/os/freebsd/zfs/spa_os.c
module/os/linux/zfs/spa_misc_os.c
module/os/windows/zfs/spa_misc_os.c
module/zfs/spa.c

im working on slowly getting the windows branch to be even with upstream
this was the first conflict I had to solve

merge spa from upstream

---

include/os/windows/spl/sys/uio.h
lib/libspl/os/windows/posix.c
lib/libzutil/os/windows/zutil_import_os.c
module/os/windows/spl/spl-vnode.c

remove " \\" that were used on things other than defines

clean up cstyle problems

---

cmd/zdb/zdb.c

free zalloc'd memory at every return

---

.github/workflows/windows-build-test.yml

This tries to install zfs after building it to catch errors that occur on load.

Install after building in workflow

---

.github/workflows/windows-build-test.yml

Add winnbtrfs tests to build test

---

.github/workflows/windows-build-test.yml

Add timeouts to workflow so that they return a failure in a reasonable amount of time.

Add timeouts to workflow

---

module/os/windows/spl/spl-mutex.c

https://github.com/openzfsonwindows/openzfs/issues/136

Remove check for locking against self

---

.github/workflows/windows-build-test.yml

add readme header

---

contrib/windows/Inno.Setup/ZFSInstall-debug.iss

This adds other debug symbols to the installer.
But increases the size from 14mb to 34mb.

Add debug symbols to inno script

---

.github/workflows/windows-build-test.yml
contrib/windows/Inno.Setup/ZFSInstall-debug.iss

Sign the installer

---

module/os/windows/README.md

update with VS2022 and wdk 11

---

include/os/freebsd/spl/sys/atomic.h
include/os/linux/spl/sys/vmsystm.h
include/os/windows/spl/sys/atomic.h
lib/libspl/atomic.c
lib/libspl/include/atomic.h

Windows: Add membar_sync

---

include/os/windows/spl/sys/atomic.h

https://github.com/openzfsonwindows/openzfs/issues/155 https://github.com/illumos/illumos-gate/blob/master/usr/src/common/atomic/amd64/atomic.s

Windows: Use proper locks for membar

---

cmd/zfs/zfs_main.c
cmd/ztest.c
config/Rules.am
include/os/freebsd/spl/sys/kstat.h
include/os/linux/spl/sys/kstat.h
include/os/windows/spl/sys/kstat.h
lib/libzfs/libzfs_dataset.c
lib/libzfs/libzfs_diff.c
lib/libzpool/taskq.c
module/os/freebsd/spl/callb.c
module/os/freebsd/zfs/zfs_vfsops.c
module/os/linux/spl/spl-kmem-cache.c
module/os/linux/spl/spl-kstat.c
module/os/linux/spl/spl-thread.c
module/os/linux/spl/spl-zone.c
module/os/windows/spl/spl-kmem.c
module/os/windows/spl/spl-kstat.c
module/os/windows/spl/spl-lookasidelist.c
module/os/windows/spl/spl-taskq.c
module/zfs/dsl_dir.c
module/zfs/dsl_prop.c
module/zfs/spa_misc.c
module/zfs/zcp_get.c
module/zfs/zfs_ioctl.c
module/zfs/zio_inject.c
tests/zfs-tests/cmd/draid.c
tests/zfs-tests/cmd/zfs_diff-socket.c

Windows: transition to strlcpy

---

CMakeLists.txt

Part of a project to collect loose code from around the different repositories and get it upstreamed
prevent the incorrect build error at the end of a build.

Prevent the build error at the end of a build

---

module/os/windows/zfs/zvol_os.c

Part of a project to collect loose code from around the different repositories and get it upstreamed
This changes the threads to 32 like other operating systems

increased the zvol taskq threads to 32 as in ZFSin

---

.github/workflows/windows-build-test.yml

Test against winfstest to try and identify incorrect behaviour

Add more tests to the workflow

---

.github/workflows/codeql-windows.yml

ala https://github.com/openzfs/zfs/pull/14087

codeql workflow for static analysis

---

lib/libefi/rdwr_efi_windows.c
lib/libspl/include/os/windows/sys/types.h
lib/libspl/include/sys/types.h
lib/libspl/include/umem.h
lib/libzutil/zutil_import.c

Use upstream umem_free_aligned instead of our posix_memalign_free

---

cmd/zed/zed_event.c
include/os/freebsd/spl/sys/kmem.h
include/os/linux/spl/sys/kmem.h
include/os/windows/spl/sys/kmem.h
include/sys/spa.h
include/sys/zfs_context.h
lib/libspl/os/linux/zone.c
lib/libzfs/os/freebsd/libzfs_compat.c
lib/libzpool/kernel.c
module/os/freebsd/spl/spl_string.c
module/os/linux/zfs/zfs_sysfs.c
module/os/windows/spl/spl-kmem.c
module/zfs/dataset_kstats.c
module/zfs/spa_misc.c
module/zfs/vdev_raidz_math.c
module/zfs/zfs_chksum.c

I'm not exactly sure why this isn't compiling so I've put it here to get some feedback

Introduce kmem_scnprintf() 

---

lib/libspl/os/windows/posix.c
lib/libzutil/os/windows/zutil_import_os.c

use HTOI macro when casting handles

---

.github/workflows/windows-build-test.yml

Test uninstall of OpenZFS

---

contrib/windows/Inno.Setup/ZFSInstall-debug.iss
contrib/windows/parsedump/README.md
contrib/windows/parsedump/parsedump.bat
contrib/windows/parsedump/parsedump.py

A couple of scripts that will automatically extract information from crash dumps to help with the debugging of OpenZFS
I hated having to do this by hand myself so now nobody will have to.
I installed OpenZFS using the installer.
Check that the scripts were installed.
Ran the scripts.

Script for extracting crash logs

---

.github/workflows/windows-build-test.yml

Handle both types of slash

---

.github/workflows/windows-build-test.yml

Add sleep to tests

---

.github/workflows/windows-build-test.yml

Run winbtrfs tests by default

---

contrib/windows/parsedump/parsedump.bat

Use python3 on windows

---

.github/workflows/windows-build-test.yml
contrib/windows/tests/btrfstests.py
contrib/windows/tests/tests.py

Use python based tests

---

contrib/windows/tests/btrfstests.py
contrib/windows/tests/tests.py

Fix style of python tests

---

.github/workflows/windows-build-test.yml
contrib/windows/tests/winfstests.py

Use python based winfstests

---

.github/workflows/windows-build-test.yml
contrib/windows/tests/ifstest.py

Use python based ifstest

---

contrib/windows/tests/ifstest.py

Fix checkstyle

---

.github/workflows/windows-build-test.yml

Disable legacy style tests

---

.github/workflows/windows-build-test.yml

Fix github ci
